version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
